backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

locale: "it"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Tag", name: "tags", widget: "list", required: false }
      - { label: "Testo", name: "body", widget: "markdown" }
